version: '3.7'

services:

  # noteserver goes first because if client tries to ping 
  # reverse proxy and note server isn't running the proxy will crash
  noteserver:
    image: gonotesd
    build:
      context: ../project-0/cmd/GoNotesd/
      dockerfile: Dockerfile
    env_file: ../project-0/.env

  logger:
    image: logger
    volumes: 
      - /home/ubuntu/Desktop/logs:/logs
    build:
      context: ./cmd/logger/
      dockerfile: Dockerfile
    env_file: .env

  reverseproxy:
    image: rproxy
    build: 
      context: ./cmd/reverseproxy/
      dockerfile: Dockerfile
    ports:
      - 6060:6060
    env_file: .env
    depends_on: 
      - logger
      - noteserver