version: '3.7'

services:

  dns:
    image: dns
    volumes: 
      - /home/ubuntu/Desktop/logs/dns:/logs
    build:
      context: ./cmd/dns/
      dockerfile: Dockerfile
    env_file: .env

  logger:
    image: logger
    volumes: 
      - /home/ubuntu/Desktop/logs/logger:/logs
    build:
      context: ./cmd/logger/
      dockerfile: Dockerfile
    env_file: .env
    depends_on: 
      - dns

  noteserver:
    image: gonotesd
    volumes: 
      - /home/ubuntu/Desktop/notes:/notes
      - /home/ubuntu/Desktop/logs/server:/logs
    build:
      context: ../project-0/cmd/GoNotesd/
      dockerfile: Dockerfile
    env_file: ../project-0/.env
    depends_on: 
      - dns
      - logger

  reverseproxy:
    image: rproxy
    volumes: 
      - /home/ubuntu/Desktop/logs/reverseproxy:/logs
    build: 
      context: ./cmd/reverseproxy/
      dockerfile: Dockerfile
    ports:
      - 6060:6060
    env_file: .env
    depends_on: 
      - dns
      - logger
      - noteserver

  dashboard:
    image: dashboard
    volumes: 
      - /home/ubuntu/Desktop/logs/dashboard:/logs
    build:
      context: ./cmd/dashboard/
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file: .env
    depends_on: 
      - dns
      - logger
      - noteserver
      - reverseproxy